name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pipenv
      run: |
          python -m pip install --upgrade pipenv wheel
    
    - name: Install dependencies
      run: |
        pipenv install
        pipenv install pylint

    - name: Analysing the code with pylint
      run: |
        pwd
        export PYTHONPATH='~/wavaugmentate/src/wavaugmentate'
        pipenv run pylint $(git ls-files 'src/*/*.py')
        pipenv run pylint $(git ls-files 'tests/*/*.py')
